CREATE TABLE records (
    record_id TEXT PRIMARY KEY,
    target_object_id TEXT NOT NULL,
    media_type TEXT NOT NULL,
    source_platform TEXT,
    source_url_or_archive_id TEXT,
    retrieval_date TEXT NOT NULL,
    observed_post_date TEXT,
    earliest_known_circulation_date TEXT,
    estimated_creation_date TEXT,
    date_precision TEXT,
    creator_status TEXT,
    institution TEXT,
    country_or_context TEXT,
    caption_or_text TEXT,
    copyright_or_license_status TEXT,
    machine_detection_method TEXT,
    machine_visual_tier TEXT,
    machine_nominal_class TEXT,
    machine_confidence REAL,
    coder_1_visual_tier TEXT,
    coder_1_nominal_class TEXT,
    coder_1_confidence REAL,
    coder_1_notes TEXT,
    coder_2_visual_tier TEXT,
    coder_2_nominal_class TEXT,
    coder_2_confidence REAL,
    coder_2_notes TEXT,
    final_visual_tier TEXT,
    final_nominal_class TEXT,
    adjudication_notes TEXT,
    genealogy_evidence TEXT,
    configuration_version TEXT NOT NULL
);

CREATE TABLE semiotic_displacement (
    record_id TEXT NOT NULL REFERENCES records(record_id),
    comparison_id TEXT NOT NULL,
    visual_transformation_score REAL,
    contextual_reframing_score REAL,
    performative_function_shift_score REAL,
    institutional_recontextualisation_score REAL,
    interpretive_shift_score REAL,
    aggregate_delta_s REAL,
    delta_t REAL,
    delta_t_unit TEXT,
    semiotic_velocity REAL,
    coding_scheme_version TEXT NOT NULL,
    coder_confidence REAL,
    evidence_notes TEXT,
    PRIMARY KEY (record_id, comparison_id)
);

CREATE TABLE friction_coding (
    record_id TEXT PRIMARY KEY REFERENCES records(record_id),
    f1_category TEXT,
    f1_stabilising_or_destabilising TEXT,
    f1_strength REAL,
    f1_evidence TEXT,
    f2_institution TEXT,
    f2_condition TEXT,
    f2_strength REAL,
    f2_evidence TEXT,
    f3_medium TEXT,
    f3_platform TEXT,
    f3_editability TEXT,
    f3_replication_affordance TEXT,
    f3_circulation_constraint TEXT,
    f3_evidence TEXT
);
